title: Heather Lenz
logo: /assets/img/headshot.jpg
description: "Fourth-year B.Sc. student in Astrophysics and Physics at the University of Calgary, with experience in telescope operation, Python-based variable star detection, and globular cluster research at the Rothney Astrophysical Observatory and CFHT. Passionate about astronomical instrumentation and pursuing a master's degree."
theme: jekyll-theme-minimal
show_downloads: false
